from __future__ import annotations

"""Trusted bootstrap requirements for configured Dual Agents actors.

The files referenced here remain owned by the machine-wide Codex policy.  This
module only validates their presence and transports the requirement to a real
provider; it never copies policy files into a profile or accepts a model
supplied replacement path.
"""

from pathlib import Path


CANONICAL_INSTRUCTIONS_ROOT = Path(r"C:\CodexGlobal")
BOOTSTRAP_MARKER = "[DUAL_CODEX_CANONICAL_BOOTSTRAP]"


def canonical_instructions_root(root: Path | None = None) -> Path:
    """Return the canonical policy root, failing closed when it is incomplete."""

    resolved = (root or CANONICAL_INSTRUCTIONS_ROOT).expanduser()
    agents = resolved / "AGENTS.md"
    skills = resolved / "skills"
    if not agents.is_file():
        raise FileNotFoundError(f"Canonical instruction file is unavailable: {agents}")
    if not skills.is_dir():
        raise FileNotFoundError(f"Canonical skill tree is unavailable: {skills}")
    return resolved


def configured_actor_prompt(prompt: str, *, role: str) -> tuple[str, Path]:
    """Bind a phase prompt to the machine-wide bootstrap requirement.

    The marker makes the operation idempotent when a provider adapter and the
    control-plane seam both prepare the same prompt.  The role is generated by
    trusted control-plane code, never parsed from model output.
    """

    root = canonical_instructions_root()
    text = str(prompt)
    if BOOTSTRAP_MARKER in text:
        return text, root
    bootstrap = (
        f"{BOOTSTRAP_MARKER}\n"
        "Before this phase begins, read the canonical policy and select the "
        "required skills exactly as instructed. Read every selected SKILL.md "
        "completely. The canonical source is machine-owned and must not be "
        "copied or replaced by profile-local files. Fail closed if it cannot "
        f"be read: {root / 'AGENTS.md'} and {root / 'skills'}\n"
        f"Trusted configured phase role: {role}\n\n"
    )
    return bootstrap + text, root

